### ISSUE TITLE
TODO: remove hard coding of TSC

### ISSUE THREAD

**Issue by mhdawson** [mhdawson/create-node-meeting-artifacts#2]
Use parameter as opposed to hard coding TSC.

**Comment by cPhost** [comment]
@mhdawson sorry for delay i was busy with node-core-utils. I need some guidance for this, 
By removing to you mean get it from readme.md if not can you please let me know where to get it from.

**Comment by mhdawson** [comment]
What I meant was instead of hard coding it in this line:

    const meetingGroup = 'TSC';

to pull it from the arguments.  Its a pretty small change.  I may look at this tomorrow as I want to use the tool create the meeting artifacts for the Benchmarking meeting next Monday.  If you have a chance before then a PR would be welcome.

**Comment by mhdawson** [comment]
Closed by https://github.com/mhdawson/create-node-meeting-artifacts/pull/4
